[package]
name = "impossible-voice-stt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
impossible-server-core.workspace = true
impossible-voice-audio.workspace = true
impossible-voice-sherpa-sys.workspace = true

[lints]
workspace = true
