$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$scannerSource = Join-Path $repoRoot "scripts/privacy-scan.ps1"
$fixture = Join-Path ([IO.Path]::GetTempPath()) ("impossible-server-privacy-" + [guid]::NewGuid().ToString("N"))
$pwsh = (Get-Process -Id $PID).Path

$cases = @(
    [ordered]@{ name = "quoted JSON API credential"; content = ('{"api' + '_key":"ordinary-live-secret"}'); passes = $false },
    [ordered]@{ name = "quoted JSON auth credential"; content = ('{"auth' + '_token":"ordinary-live-secret"}'); passes = $false },
    [ordered]@{ name = "GPT co-author attribution"; content = ('Co-authored-by: GP' + 'T-5 <fixture@example.invalid>'); passes = $false },
    [ordered]@{ name = "Gemini generator attribution"; content = ('Generated by Gem' + 'ini'); passes = $false },
    [ordered]@{ name = "environment placeholder"; content = ('{"api' + '_key":"${API_KEY}"}'); passes = $true },
    [ordered]@{ name = "compatibility prose"; content = ('This API is compatible with GP' + 'T, Gemini, and OpenAI clients.'); passes = $true },
    [ordered]@{ name = "human co-author containing ai"; content = 'Co-authored-by: Kai Human <kai@example.invalid>'; passes = $true }
)
$selfCases = @(
    [ordered]@{ name = "private path appended to scanner"; content = ('C:' + '\Us' + 'ers\fixture\private.txt') },
    [ordered]@{ name = "hosted token appended to scanner"; content = ('gh' + 'p_' + ('a' * 30)) },
    [ordered]@{ name = "credential appended to scanner"; content = ('{"api' + '_key":"ordinary-live-secret"}') },
    [ordered]@{ name = "attribution appended to scanner"; content = ('Generated by Gem' + 'ini') }
)

try {
    New-Item -ItemType Directory -Path (Join-Path $fixture "scripts") -Force | Out-Null
    $scannerPath = Join-Path $fixture "scripts/privacy-scan.ps1"
    Copy-Item -LiteralPath $scannerSource -Destination $scannerPath
    $scannerBaseline = [IO.File]::ReadAllText($scannerPath)
    & git -C $fixture init --quiet
    if ($LASTEXITCODE -ne 0) { throw "unable to initialize privacy test fixture" }

    foreach ($case in $cases) {
        [IO.File]::WriteAllText((Join-Path $fixture "sample.txt"), $case.content, [Text.UTF8Encoding]::new($false))
        $null = & $pwsh -NoProfile -File (Join-Path $fixture "scripts/privacy-scan.ps1") 2>&1
        $passed = $LASTEXITCODE -eq 0
        if ($passed -ne $case.passes) {
            throw "privacy scanner case '$($case.name)' produced an unexpected result"
        }
    }

    [IO.File]::WriteAllText((Join-Path $fixture "sample.txt"), "safe fixture", [Text.UTF8Encoding]::new($false))
    foreach ($case in $selfCases) {
        [IO.File]::WriteAllText($scannerPath, ($scannerBaseline + "`n# " + $case.content + "`n"), [Text.UTF8Encoding]::new($false))
        $null = & $pwsh -NoProfile -File $scannerPath 2>&1
        if ($LASTEXITCODE -eq 0) {
            throw "privacy scanner self-file case '$($case.name)' was not rejected"
        }
    }

    $definitionMatch = [regex]::Match($scannerBaseline, '(?m)^[ \t]*private_home[ \t]*=.*$')
    if (-not $definitionMatch.Success) { throw "privacy scanner fixture could not find its pattern definition" }
    $internalPayload = ' # ' + ('C:' + '\Us' + 'ers\fixture\private.txt')
    $definitionMutant = $scannerBaseline.Insert(
        $definitionMatch.Index + $definitionMatch.Length,
        $internalPayload
    )
    [IO.File]::WriteAllText($scannerPath, $definitionMutant, [Text.UTF8Encoding]::new($false))
    $null = & $pwsh -NoProfile -File $scannerPath 2>&1
    if ($LASTEXITCODE -eq 0) { throw "privacy scanner accepted a payload inside a pattern definition" }

    [IO.File]::WriteAllText($scannerPath, $scannerBaseline, [Text.UTF8Encoding]::new($false))
    $null = & $pwsh -NoProfile -File $scannerPath 2>&1
    if ($LASTEXITCODE -ne 0) { throw "unmodified privacy scanner did not scan itself cleanly" }

    Write-Output "Privacy scanner adversarial cases passed."
} finally {
    if (Test-Path -LiteralPath $fixture) {
        Remove-Item -LiteralPath $fixture -Recurse -Force
    }
}
