[package]
name = "impossible-voice-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "impossible-voice"
path = "src/main.rs"

[dependencies]
impossible-server-core.workspace = true

[dev-dependencies]
impossible-server-testkit.workspace = true

[lints]
workspace = true
